<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_SocialLogin
 * @copyright   Copyright (c) 2014 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php if (Mage::helper('pslogin')->moduleEnabled() && !Mage::helper('pslogin')->hasIntegrationModules()): ?>
	<?php echo strrev('>vid/<>a/<tekcormulP yb noisnetxE otnegaM>"knalb_"=tegrat "moc.tekcormulp.erots//:sptth"=ferh "snoisnetxE 2 otnegaM ;pma& 1 otnegaM tseB"=eltit a< nigoL koobecaF & rettiwT>";retnec:ngila-txet;xp11:ezis-tnof"=elyts vid<'); ?>
<?php endif; ?>